#!/usr/bin/env python
"""
Sample configuration/run script for dns_test.py
"""

import os.path
import platform
from dnstest import do_dns_tests

# set your production/live  DNS server
SERVER_PROD = "10.188.14.124"

# set your test/staging DNS server
SERVER_TEST = "10.188.8.130"

# whether or not we should have reverse DNS for valid A records
HAVE_REVERSE_DNS = True

# set this to your default domain, to be appended to requests that aren't a FQDN
DEFAULT_DOMAIN = ".example.com"

tests = {}

# new records that were added - A or CNAME
tests['added'] = {}
tests['added']['newhostname'] = '1.2.3.4'
tests['added']['newcname'] = 'newhostname'

# one A or CNAME added, another removed, with the same value
tests['changed'] = {}
tests['changed']['oldname'] = 'newname'

# records that were removed - A or CNAME
tests['removed'] = []
tests['removed'] = ['removedname1', 'removedname2']

print "# output generated by dns_test.py running with config file %s on %s" % (os.path.abspath(__file__), platform.node())

do_dns_tests(tests, SERVER_TEST, SERVER_PROD, DEFAULT_DOMAIN, HAVE_REVERSE_DNS)
