# tests for dnstest_config.py

import pytest
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + '/../')
import shutil
import os.path
import os

import dnstest_config


class TestConfigMethods:
    """
    Class to test the configuration-related methods in dnstest_config
    """

    @pytest.fixture
    def save_user_config(self, request):
        """
        Rename any existing configuration files prior to testing
        """
        if os.path.exists("dnstest.conf"):
            shutil.move(os.path.abspath("dnstest.conf"), os.path.abspath("dnstest.conf.pretest"))
        if os.path.exists(os.path.expanduser("~/.dnstest.conf")):
            shutil.move(os.path.expanduser("~/.dnstest.conf"), os.path.expanduser("~/.dnstest.conf.pretest"))
        request.addfinalizer(self.restore_user_config)

    def restore_user_config(self):
        """
        Remove any config files generated by testing, and restore previous configs
        """
        # teardown
        if os.path.exists("dnstest.conf"):
            os.remove("dnstest.conf")
        if os.path.exists(os.path.expanduser("~/.dnstest.conf")):
            os.remove(os.path.expanduser("~/.dnstest.conf"))

        if os.path.exists("dnstest.conf.pretest"):
            shutil.move(os.path.abspath("dnstest.conf.pretest"), os.path.abspath("dnstest.conf"))
        if os.path.exists(os.path.expanduser("~/.dnstest.conf.pretest")):
            shutil.move(os.path.expanduser("~/.dnstest.conf.pretest"), os.path.expanduser("~/.dnstest.conf"))
        return True

    def test_find_no_config_file(self, save_user_config):
        assert dnstest_config.find_config_file() == None

    def test_find_main_config_file(self, save_user_config):
        fpath = os.path.abspath("dnstest.conf")
        fh = open(fpath, 'w')
        fh.write("test_find_main_config_file")
        fh.close()
        assert dnstest_config.find_config_file() == fpath

    def test_find_dot_config_file(self, save_user_config):
        fpath = os.path.expanduser("~/.dnstest.conf")
        fh = open(fpath, 'w')
        fh.write("test_find_dot_config_file")
        fh.close()
        assert dnstest_config.find_config_file() == fpath
